// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBclBvU01BWf0471g1nhCvnSguWOB3vgj8',
    appId: '1:389758528478:web:cb803fd46d3b009d56cb4f',
    messagingSenderId: '389758528478',
    projectId: 'fire-try-first',
    authDomain: 'fire-try-first.firebaseapp.com',
    databaseURL: 'https://fire-try-first-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-try-first.appspot.com',
    measurementId: 'G-QFQGJRVPMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80-TxS5YwHPOO8rDm-bh4kLEQcxme7S8',
    appId: '1:389758528478:android:9352b2c66477679a56cb4f',
    messagingSenderId: '389758528478',
    projectId: 'fire-try-first',
    databaseURL: 'https://fire-try-first-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-try-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcyzuExASceNjpVMak1xmew4pZ2SD1ggI',
    appId: '1:389758528478:ios:d37675c0a8a30de456cb4f',
    messagingSenderId: '389758528478',
    projectId: 'fire-try-first',
    databaseURL: 'https://fire-try-first-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-try-first.appspot.com',
    iosBundleId: 'com.example.chatBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcyzuExASceNjpVMak1xmew4pZ2SD1ggI',
    appId: '1:389758528478:ios:d37675c0a8a30de456cb4f',
    messagingSenderId: '389758528478',
    projectId: 'fire-try-first',
    databaseURL: 'https://fire-try-first-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-try-first.appspot.com',
    iosBundleId: 'com.example.chatBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBclBvU01BWf0471g1nhCvnSguWOB3vgj8',
    appId: '1:389758528478:web:c3e9e126257447cd56cb4f',
    messagingSenderId: '389758528478',
    projectId: 'fire-try-first',
    authDomain: 'fire-try-first.firebaseapp.com',
    databaseURL: 'https://fire-try-first-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-try-first.appspot.com',
    measurementId: 'G-VPMP5B7QHS',
  );
}
